{
  "formatVersion": "1.1",
  "component": {
    "group": "com.utopia-rise",
    "module": "godot-core-library-debug",
    "version": "0.14.3-4.5.1-92ac75f-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.13"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "com.utopia-rise",
          "module": "common",
          "version": {
            "requires": "0.14.3-4.5.1-92ac75f-SNAPSHOT"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.10"
          }
        }
      ],
      "files": [
        {
          "name": "godot-core-library-debug-0.14.3-4.5.1-92ac75f-SNAPSHOT.jar",
          "url": "godot-core-library-debug-0.14.3-4.5.1-92ac75f-SNAPSHOT.jar",
          "size": 836400,
          "sha512": "82b2bbe857302311d8425a1b0980a15d0f54bf886a2b6a09db26e0102ee6e66a2725a8edb028c72a74bef4ead4fecc65ae7793bbfd2646a34c6d00921f68222f",
          "sha256": "f4e5f7f3da5ed5d5b717f2ec4c95262c9e19c333b7ee7bd7c1d01443cac7e637",
          "sha1": "7f24a63f2e0629b77bd15d034171d34f02826676",
          "md5": "0b6d9769a4aaac1c4f23093589726dc4"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "com.utopia-rise",
          "module": "godot-internal-library-debug",
          "version": {
            "requires": "0.14.3-4.5.1-92ac75f-SNAPSHOT"
          }
        },
        {
          "group": "com.utopia-rise",
          "module": "common",
          "version": {
            "requires": "0.14.3-4.5.1-92ac75f-SNAPSHOT"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.10"
          }
        }
      ],
      "files": [
        {
          "name": "godot-core-library-debug-0.14.3-4.5.1-92ac75f-SNAPSHOT.jar",
          "url": "godot-core-library-debug-0.14.3-4.5.1-92ac75f-SNAPSHOT.jar",
          "size": 836400,
          "sha512": "82b2bbe857302311d8425a1b0980a15d0f54bf886a2b6a09db26e0102ee6e66a2725a8edb028c72a74bef4ead4fecc65ae7793bbfd2646a34c6d00921f68222f",
          "sha256": "f4e5f7f3da5ed5d5b717f2ec4c95262c9e19c333b7ee7bd7c1d01443cac7e637",
          "sha1": "7f24a63f2e0629b77bd15d034171d34f02826676",
          "md5": "0b6d9769a4aaac1c4f23093589726dc4"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "godot-core-library-debug-0.14.3-4.5.1-92ac75f-SNAPSHOT-sources.jar",
          "url": "godot-core-library-debug-0.14.3-4.5.1-92ac75f-SNAPSHOT-sources.jar",
          "size": 173783,
          "sha512": "e4d93bb726d902a137b794a20a92f9e2a21bbe3d429e3db8d75e9f58b2cac7bcdbe0b95ce528c5a3537532df1182f9e3ab1af6608923d166a1483922f453cc22",
          "sha256": "1f44306d569bc2a807eb7b6e8f088d8082caafa56625e0b97a9949dcc498c6be",
          "sha1": "6311aa0c2a152a3a99c4e83766f60eb129184226",
          "md5": "95cf49fb4e2497df3eb2ddaed8d0703f"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "godot-core-library-debug-0.14.3-4.5.1-92ac75f-SNAPSHOT-javadoc.jar",
          "url": "godot-core-library-debug-0.14.3-4.5.1-92ac75f-SNAPSHOT-javadoc.jar",
          "size": 261,
          "sha512": "f3dd22310902d1272d1fe1089999197f7b24e9175e10fd4c6ab1ab30de2489049df2ca07a7aab6c3ceede42315d6ddfc72a5b3d0cbcc3cadece1bb0fe7c76fa4",
          "sha256": "10f2c76af3b3f3788b62c580671c4b214e2e7fd611a1f7ae2f4de237ac86b09d",
          "sha1": "90776b3343d65bda3422c14a930b7309f0cc25cd",
          "md5": "389e4a9d56323bc7182d4177bc099998"
        }
      ]
    }
  ]
}
