{
  "formatVersion": "1.1",
  "component": {
    "group": "com.utopia-rise",
    "module": "godot-coroutine-library-debug",
    "version": "0.14.3-4.5.1-92ac75f-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.13"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.10.1"
          }
        },
        {
          "group": "com.utopia-rise",
          "module": "common",
          "version": {
            "requires": "0.14.3-4.5.1-92ac75f-SNAPSHOT"
          }
        },
        {
          "group": "com.utopia-rise",
          "module": "godot-core-library-debug",
          "version": {
            "requires": "0.14.3-4.5.1-92ac75f-SNAPSHOT"
          }
        },
        {
          "group": "com.utopia-rise",
          "module": "godot-api-library-debug",
          "version": {
            "requires": "0.14.3-4.5.1-92ac75f-SNAPSHOT"
          }
        },
        {
          "group": "com.utopia-rise",
          "module": "godot-extension-library-debug",
          "version": {
            "requires": "0.14.3-4.5.1-92ac75f-SNAPSHOT"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.10"
          }
        }
      ],
      "files": [
        {
          "name": "godot-coroutine-library-debug-0.14.3-4.5.1-92ac75f-SNAPSHOT.jar",
          "url": "godot-coroutine-library-debug-0.14.3-4.5.1-92ac75f-SNAPSHOT.jar",
          "size": 108611,
          "sha512": "d7364c3e5f5b778d50ce3e27af3d13471f1a21e37428c3c73333fdeec336b93f50e4172a05bb5f145be6bbfbeb917397926b87729b4527ba7ee00775af087ebe",
          "sha256": "211a002de91a91cca8c0a4329bde53a7211a3b145f51f8365564c60d00ede828",
          "sha1": "549ab664b0addde1ce43c88bd5216f407067a8d5",
          "md5": "7857309ad6a41fc9b096d6790b2bae4b"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "com.utopia-rise",
          "module": "godot-internal-library-debug",
          "version": {
            "requires": "0.14.3-4.5.1-92ac75f-SNAPSHOT"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.10.1"
          }
        },
        {
          "group": "com.utopia-rise",
          "module": "common",
          "version": {
            "requires": "0.14.3-4.5.1-92ac75f-SNAPSHOT"
          }
        },
        {
          "group": "com.utopia-rise",
          "module": "godot-core-library-debug",
          "version": {
            "requires": "0.14.3-4.5.1-92ac75f-SNAPSHOT"
          }
        },
        {
          "group": "com.utopia-rise",
          "module": "godot-api-library-debug",
          "version": {
            "requires": "0.14.3-4.5.1-92ac75f-SNAPSHOT"
          }
        },
        {
          "group": "com.utopia-rise",
          "module": "godot-extension-library-debug",
          "version": {
            "requires": "0.14.3-4.5.1-92ac75f-SNAPSHOT"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.10"
          }
        }
      ],
      "files": [
        {
          "name": "godot-coroutine-library-debug-0.14.3-4.5.1-92ac75f-SNAPSHOT.jar",
          "url": "godot-coroutine-library-debug-0.14.3-4.5.1-92ac75f-SNAPSHOT.jar",
          "size": 108611,
          "sha512": "d7364c3e5f5b778d50ce3e27af3d13471f1a21e37428c3c73333fdeec336b93f50e4172a05bb5f145be6bbfbeb917397926b87729b4527ba7ee00775af087ebe",
          "sha256": "211a002de91a91cca8c0a4329bde53a7211a3b145f51f8365564c60d00ede828",
          "sha1": "549ab664b0addde1ce43c88bd5216f407067a8d5",
          "md5": "7857309ad6a41fc9b096d6790b2bae4b"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "godot-coroutine-library-debug-0.14.3-4.5.1-92ac75f-SNAPSHOT-sources.jar",
          "url": "godot-coroutine-library-debug-0.14.3-4.5.1-92ac75f-SNAPSHOT-sources.jar",
          "size": 5737,
          "sha512": "ca7c3af2f3f0f55a5da2ea130f67590059b1c45c9131bf286128b0f960150a4aa8f368ebad1419ee8003accd8fc8dd019eb19ca22fced12fadd7e44e368216c9",
          "sha256": "3629755e5301c2ba6002ef6f66d48fe2be2966077301e7f7c5443b80c25a429d",
          "sha1": "c9133aac4afb249774400df05fbd2f968ac766dd",
          "md5": "509c2f2a66dee23d238fc4982266cc60"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "godot-coroutine-library-debug-0.14.3-4.5.1-92ac75f-SNAPSHOT-javadoc.jar",
          "url": "godot-coroutine-library-debug-0.14.3-4.5.1-92ac75f-SNAPSHOT-javadoc.jar",
          "size": 261,
          "sha512": "1c7ab2a42f3d0a425498adfefb0619523400b0e147e97544e332eb8f4b85e0696ee7215d20aa908104fb1d6cad64f28d628d7985224ef07dbccb76a015b92d2f",
          "sha256": "14b5116dffc6e16431c7e6f7a531286d7e79bb3ec9e40e0899f4a4266abca56c",
          "sha1": "971f7ef89e1e8ea382dbe5c894405e2e2b5062bb",
          "md5": "14300134d0cc65208305ba20b79f5faf"
        }
      ]
    }
  ]
}
