{
  "formatVersion": "1.1",
  "component": {
    "group": "com.utopia-rise",
    "module": "godot-entry-generator",
    "version": "0.14.3-4.5.1-92ac75f-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.13"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.10"
          }
        }
      ],
      "files": [
        {
          "name": "godot-entry-generator-0.14.3-4.5.1-92ac75f-SNAPSHOT.jar",
          "url": "godot-entry-generator-0.14.3-4.5.1-92ac75f-SNAPSHOT.jar",
          "size": 182541,
          "sha512": "bd6fd52b1eb8b3130c6904d35c2551c513a8aa3c305688563bd22f0d4c442066253269d3ef7140e4e3637ac1699e86f0f1d2c0f5fe55dba596ce1459d1fce5bd",
          "sha256": "c2bad104e99cdd0aa7e1fbcf6f217499331775400f3dd375d9f98504e8862e28",
          "sha1": "8349da56b01e84e53634b290c0b1fc738bb85c3d",
          "md5": "d97f24ad1205559502e671b1d4aab7d7"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "com.utopia-rise",
          "module": "tools-common",
          "version": {
            "requires": "0.14.3-4.5.1-92ac75f-SNAPSHOT"
          }
        },
        {
          "group": "com.utopia-rise",
          "module": "godot-bootstrap-library-debug",
          "version": {
            "requires": "0.14.3-4.5.1-92ac75f-SNAPSHOT"
          }
        },
        {
          "group": "com.squareup",
          "module": "kotlinpoet",
          "version": {
            "requires": "1.12.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.10"
          }
        }
      ],
      "files": [
        {
          "name": "godot-entry-generator-0.14.3-4.5.1-92ac75f-SNAPSHOT.jar",
          "url": "godot-entry-generator-0.14.3-4.5.1-92ac75f-SNAPSHOT.jar",
          "size": 182541,
          "sha512": "bd6fd52b1eb8b3130c6904d35c2551c513a8aa3c305688563bd22f0d4c442066253269d3ef7140e4e3637ac1699e86f0f1d2c0f5fe55dba596ce1459d1fce5bd",
          "sha256": "c2bad104e99cdd0aa7e1fbcf6f217499331775400f3dd375d9f98504e8862e28",
          "sha1": "8349da56b01e84e53634b290c0b1fc738bb85c3d",
          "md5": "d97f24ad1205559502e671b1d4aab7d7"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "godot-entry-generator-0.14.3-4.5.1-92ac75f-SNAPSHOT-sources.jar",
          "url": "godot-entry-generator-0.14.3-4.5.1-92ac75f-SNAPSHOT-sources.jar",
          "size": 49277,
          "sha512": "c981d07cc2cc18515830f64fc4776ac72156d7fafda7b2303cad261e685027f4fcdbca8d51728b3c78860e9dc8fd4bb1427435ca5ececec0c74ab45dbcc9cf37",
          "sha256": "081b7827a7b853e7237a602139110f4a1ff89c675570947c35e5b5a05073e27b",
          "sha1": "cb7f9fdebf784c149eeea895fc1ad76f6ae7e563",
          "md5": "4f19e29677d75e8dd0a3d19118a796ac"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "godot-entry-generator-0.14.3-4.5.1-92ac75f-SNAPSHOT-javadoc.jar",
          "url": "godot-entry-generator-0.14.3-4.5.1-92ac75f-SNAPSHOT-javadoc.jar",
          "size": 261,
          "sha512": "1c7ab2a42f3d0a425498adfefb0619523400b0e147e97544e332eb8f4b85e0696ee7215d20aa908104fb1d6cad64f28d628d7985224ef07dbccb76a015b92d2f",
          "sha256": "14b5116dffc6e16431c7e6f7a531286d7e79bb3ec9e40e0899f4a4266abca56c",
          "sha1": "971f7ef89e1e8ea382dbe5c894405e2e2b5062bb",
          "md5": "14300134d0cc65208305ba20b79f5faf"
        }
      ]
    }
  ]
}
