{
  "formatVersion": "1.1",
  "component": {
    "group": "com.utopia-rise",
    "module": "common",
    "version": "0.14.3-4.5.1-92ac75f-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.13"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.10"
          }
        }
      ],
      "files": [
        {
          "name": "common-0.14.3-4.5.1-92ac75f-SNAPSHOT.jar",
          "url": "common-0.14.3-4.5.1-92ac75f-SNAPSHOT.jar",
          "size": 29724,
          "sha512": "9871df0f46bb308f71b49bf014f2d472a1c5daa531ebf724d50b2ce88feaee68598cc342216db9ad0d0652fa62d7e80a85833391f2bd145bbe87fda298b64d81",
          "sha256": "354e8a6d7f6ee1fdff2d7077888ecc08eb9fac9f101636740c5080ed567da928",
          "sha1": "8ac77c3809708732a5c7a75f3936aa02eb037766",
          "md5": "bf97ceec23674814d320d42b1c5a75bd"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.10"
          }
        }
      ],
      "files": [
        {
          "name": "common-0.14.3-4.5.1-92ac75f-SNAPSHOT.jar",
          "url": "common-0.14.3-4.5.1-92ac75f-SNAPSHOT.jar",
          "size": 29724,
          "sha512": "9871df0f46bb308f71b49bf014f2d472a1c5daa531ebf724d50b2ce88feaee68598cc342216db9ad0d0652fa62d7e80a85833391f2bd145bbe87fda298b64d81",
          "sha256": "354e8a6d7f6ee1fdff2d7077888ecc08eb9fac9f101636740c5080ed567da928",
          "sha1": "8ac77c3809708732a5c7a75f3936aa02eb037766",
          "md5": "bf97ceec23674814d320d42b1c5a75bd"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "common-0.14.3-4.5.1-92ac75f-SNAPSHOT-sources.jar",
          "url": "common-0.14.3-4.5.1-92ac75f-SNAPSHOT-sources.jar",
          "size": 8686,
          "sha512": "796ab9d0124a84fdc2470894ed8c46adcdc487df2ffe9d9772cbf9e67a52058b43fa7c4bd0eda0d499155791f16ddcc4c12f63ead3bdc41e47b1436995d84667",
          "sha256": "a1b4f321c9927da961d88bdda2b1b50d28da7ae2f6ec6b38af03a39810642dd4",
          "sha1": "ff87bd71439f0ba168587ceedd762799549bd8e6",
          "md5": "fca548b879b3385fa289a670dcf30029"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "common-0.14.3-4.5.1-92ac75f-SNAPSHOT-javadoc.jar",
          "url": "common-0.14.3-4.5.1-92ac75f-SNAPSHOT-javadoc.jar",
          "size": 261,
          "sha512": "89091997cb5c0caed5c651c1cb708b85b549d349508857c7a2d558dec5fab30a153250968f5eb6703e6c1e1dd11689c8536c4aee5ef5dd49743cfcf4c8174027",
          "sha256": "bb895823fad354aab04e1d12a897b0229cad18a99cee4be0303153c38ddebe92",
          "sha1": "0b64db4a772f76d6f5ad5b43185535a97931d6f7",
          "md5": "302d8c8a06b67ad0f7d61db9092c8041"
        }
      ]
    }
  ]
}
