{
  "formatVersion": "1.1",
  "component": {
    "group": "com.utopia-rise",
    "module": "godot-plugins-common",
    "version": "0.13.0-4.4.1-afac9a3-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.13"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.10"
          }
        }
      ],
      "files": [
        {
          "name": "godot-plugins-common-0.13.0-4.4.1-afac9a3-SNAPSHOT-base.jar",
          "url": "godot-plugins-common-0.13.0-4.4.1-afac9a3-SNAPSHOT-base.jar",
          "size": 4729,
          "sha512": "2ddf093d1eb6e9cc76bb40c7fc57f45d7437ce29d11b369196c7a579e3ee9e729ad0a850dd32e06ee7fcf231efab7049eb60081254cdc48a4c941c4f8e9618c7",
          "sha256": "4c4f9880fd6b79946996d76522be1da31031b18f6ef2c04234075b9f04df5fbb",
          "sha1": "6e955ecd5d2c8a8df76b2c7b6417289df3bf7a1e",
          "md5": "e0da4dce7b924467bc3872a33fdfcefe"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "com.utopia-rise",
          "module": "godot-build-props",
          "version": {
            "requires": "0.13.0-4.4.1-afac9a3-SNAPSHOT"
          }
        },
        {
          "group": "com.utopia-rise",
          "module": "tools-common",
          "version": {
            "requires": "0.13.0-4.4.1-afac9a3-SNAPSHOT"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.10"
          }
        }
      ],
      "files": [
        {
          "name": "godot-plugins-common-0.13.0-4.4.1-afac9a3-SNAPSHOT-base.jar",
          "url": "godot-plugins-common-0.13.0-4.4.1-afac9a3-SNAPSHOT-base.jar",
          "size": 4729,
          "sha512": "2ddf093d1eb6e9cc76bb40c7fc57f45d7437ce29d11b369196c7a579e3ee9e729ad0a850dd32e06ee7fcf231efab7049eb60081254cdc48a4c941c4f8e9618c7",
          "sha256": "4c4f9880fd6b79946996d76522be1da31031b18f6ef2c04234075b9f04df5fbb",
          "sha1": "6e955ecd5d2c8a8df76b2c7b6417289df3bf7a1e",
          "md5": "e0da4dce7b924467bc3872a33fdfcefe"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "godot-plugins-common-0.13.0-4.4.1-afac9a3-SNAPSHOT-sources.jar",
          "url": "godot-plugins-common-0.13.0-4.4.1-afac9a3-SNAPSHOT-sources.jar",
          "size": 2075,
          "sha512": "78aff4c90e6e8d2fca8189174ffa907bdeae03e7bee2bd3e7564050afaf1e2367bf05f40dd3c91d73257de4422790b44de9559974f257ecd22620c16441b10c2",
          "sha256": "ed7a1ce84eefec8f6d14dbd7f3b01a3057e10f4e1a8b63163290c1146dffd181",
          "sha1": "6304c572833fb03cc558a22e7f8f7989cfa97163",
          "md5": "3b78d5278c33f8a7c981ca15db78ef66"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "godot-plugins-common-0.13.0-4.4.1-afac9a3-SNAPSHOT-javadoc.jar",
          "url": "godot-plugins-common-0.13.0-4.4.1-afac9a3-SNAPSHOT-javadoc.jar",
          "size": 261,
          "sha512": "03c41f7c4900ae3fb06f4d03720f7f1d233e8e675d4ffad1c3b41d562819660742b05d630592b1aae3949869b31ba498c4614f9f627a32c1f6fb5685517782d8",
          "sha256": "93eb86927f009e8ce123a32b0bd41c99e70e11a9a93cb1379c41f2d4c8f1a5c7",
          "sha1": "f9c5c208f7db5fd9d3aeec36be6d812dde6f90bc",
          "md5": "12b61d6882cb90117f7a1d66adac9a7e"
        }
      ]
    }
  ]
}
