{
  "formatVersion": "1.1",
  "component": {
    "group": "com.utopia-rise",
    "module": "godot-gradle-plugin",
    "version": "0.14.3-4.5.1-92ac75f-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.13"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.10"
          }
        }
      ],
      "files": [
        {
          "name": "godot-gradle-plugin-0.14.3-4.5.1-92ac75f-SNAPSHOT.jar",
          "url": "godot-gradle-plugin-0.14.3-4.5.1-92ac75f-SNAPSHOT.jar",
          "size": 123585,
          "sha512": "9994f71dfd2c80f32d1346875e043c1477c0fc99eb191b6040aab6bb5badfbb49229ab1995e0888ef7798cab8cfed561f83d0cfd7e78e526bcd164b7ea03f91b",
          "sha256": "380d4171cfbca6f8647d313a528b24b82299adfe54e697b810e2ed565cc8fe45",
          "sha1": "85aafa414addb0941e922ecfe1a4cb7b1515dc35",
          "md5": "6395a63d4cacb8a53783b9cec198a97c"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-gradle-plugin",
          "version": {
            "requires": "2.1.10"
          }
        },
        {
          "group": "com.gradleup.shadow",
          "module": "shadow-gradle-plugin",
          "version": {
            "requires": "8.3.6"
          }
        },
        {
          "group": "org.jetbrains.gradle.plugin.idea-ext",
          "module": "org.jetbrains.gradle.plugin.idea-ext.gradle.plugin",
          "version": {
            "requires": "1.1.10"
          }
        },
        {
          "group": "com.utopia-rise",
          "module": "godot-build-props",
          "version": {
            "requires": "0.14.3-4.5.1-92ac75f-SNAPSHOT"
          }
        },
        {
          "group": "com.utopia-rise",
          "module": "godot-plugins-common",
          "version": {
            "requires": "0.14.3-4.5.1-92ac75f-SNAPSHOT"
          }
        },
        {
          "group": "com.utopia-rise",
          "module": "tools-common",
          "version": {
            "requires": "0.14.3-4.5.1-92ac75f-SNAPSHOT"
          }
        },
        {
          "group": "com.utopia-rise",
          "module": "godot-class-graph-symbol-processor",
          "version": {
            "requires": "0.14.3-4.5.1-92ac75f-SNAPSHOT"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.10"
          }
        }
      ],
      "files": [
        {
          "name": "godot-gradle-plugin-0.14.3-4.5.1-92ac75f-SNAPSHOT.jar",
          "url": "godot-gradle-plugin-0.14.3-4.5.1-92ac75f-SNAPSHOT.jar",
          "size": 123585,
          "sha512": "9994f71dfd2c80f32d1346875e043c1477c0fc99eb191b6040aab6bb5badfbb49229ab1995e0888ef7798cab8cfed561f83d0cfd7e78e526bcd164b7ea03f91b",
          "sha256": "380d4171cfbca6f8647d313a528b24b82299adfe54e697b810e2ed565cc8fe45",
          "sha1": "85aafa414addb0941e922ecfe1a4cb7b1515dc35",
          "md5": "6395a63d4cacb8a53783b9cec198a97c"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "godot-gradle-plugin-0.14.3-4.5.1-92ac75f-SNAPSHOT-sources.jar",
          "url": "godot-gradle-plugin-0.14.3-4.5.1-92ac75f-SNAPSHOT-sources.jar",
          "size": 39697,
          "sha512": "82a3ed612fd805557852000b4f4f746b5d6731d155ce53dea44b83db3cd18306667c9bad73b3a6242032d7d7f1ac9971c0147c0c98e572ad1483936650283e13",
          "sha256": "5176672f68b3fdc7e4d885e052cf6e9bab463e73b2314fb62eb1e76aa2fe7240",
          "sha1": "d3ca4d620340d81505ddb83072705e3372322395",
          "md5": "29313550517f4b77a4a7b003f694e997"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "godot-gradle-plugin-0.14.3-4.5.1-92ac75f-SNAPSHOT-javadoc.jar",
          "url": "godot-gradle-plugin-0.14.3-4.5.1-92ac75f-SNAPSHOT-javadoc.jar",
          "size": 261,
          "sha512": "7e0c33aee3fb88a06c41ed081ee88b03eb6e310a59d1824b1104a6254c9098c4c7bfd0730583b4d477f760d4a5347e7c0a6164debf3daffad137ff2640ab4907",
          "sha256": "d605369219cf2d495932c378ef67028d89d5aaf9b10329bc3efefba1995702a9",
          "sha1": "5baccf52343a161602ea90b8375d8b2fada51f17",
          "md5": "064bf49bd666cdf325f1a6dd32cee7f4"
        }
      ]
    }
  ]
}
