{
  "formatVersion": "1.1",
  "component": {
    "group": "com.utopia-rise",
    "module": "godot-class-graph-symbol-processor",
    "version": "0.14.3-4.5.1-92ac75f-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.13"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.slf4j",
          "module": "slf4j-api",
          "version": {
            "requires": "1.7.36"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.10"
          }
        }
      ],
      "files": [
        {
          "name": "godot-class-graph-symbol-processor-0.14.3-4.5.1-92ac75f-SNAPSHOT.jar",
          "url": "godot-class-graph-symbol-processor-0.14.3-4.5.1-92ac75f-SNAPSHOT.jar",
          "size": 61842,
          "sha512": "dc655ee1491fddd5bf6bf0bdd0d5a969dc459c0e0469e05e083cb91a5d09558e67a3d22800032758ba68cf9260a82dff47d0208f3dd6c81f13ab2ef689c399d6",
          "sha256": "ffd9d168105d1c068f935ff6cf103c31a46300b8e0a28ee357ccf9d6ba74bf40",
          "sha1": "79345e395675eda4df5c9bc2a6455fb15ff1641e",
          "md5": "1847c84a339dc9d97d5f365632be45d5"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "com.utopia-rise",
          "module": "tools-common",
          "version": {
            "requires": "0.14.3-4.5.1-92ac75f-SNAPSHOT"
          }
        },
        {
          "group": "com.utopia-rise",
          "module": "godot-bootstrap-library-debug",
          "version": {
            "requires": "0.14.3-4.5.1-92ac75f-SNAPSHOT"
          }
        },
        {
          "group": "com.utopia-rise",
          "module": "godot-entry-generator",
          "version": {
            "requires": "0.14.3-4.5.1-92ac75f-SNAPSHOT"
          }
        },
        {
          "group": "io.github.classgraph",
          "module": "classgraph",
          "version": {
            "requires": "4.8.179"
          }
        },
        {
          "group": "org.slf4j",
          "module": "slf4j-api",
          "version": {
            "requires": "1.7.36"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.10"
          }
        }
      ],
      "files": [
        {
          "name": "godot-class-graph-symbol-processor-0.14.3-4.5.1-92ac75f-SNAPSHOT.jar",
          "url": "godot-class-graph-symbol-processor-0.14.3-4.5.1-92ac75f-SNAPSHOT.jar",
          "size": 61842,
          "sha512": "dc655ee1491fddd5bf6bf0bdd0d5a969dc459c0e0469e05e083cb91a5d09558e67a3d22800032758ba68cf9260a82dff47d0208f3dd6c81f13ab2ef689c399d6",
          "sha256": "ffd9d168105d1c068f935ff6cf103c31a46300b8e0a28ee357ccf9d6ba74bf40",
          "sha1": "79345e395675eda4df5c9bc2a6455fb15ff1641e",
          "md5": "1847c84a339dc9d97d5f365632be45d5"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "godot-class-graph-symbol-processor-0.14.3-4.5.1-92ac75f-SNAPSHOT-sources.jar",
          "url": "godot-class-graph-symbol-processor-0.14.3-4.5.1-92ac75f-SNAPSHOT-sources.jar",
          "size": 16054,
          "sha512": "f682f9806f455de80d7a455fb8610af38aed8ce4e99ff45309c9f3780eb3a1878896fcb005bd0dbe6252efbab4c2176ec90f4597073d87c82082e2fa8fd43889",
          "sha256": "e206098be2eb4c696208e60bdc4bd957e43e1f523256c550f0df2a38970b60e9",
          "sha1": "bd225685879705111f11139f1f3e7b5f39ea0ec6",
          "md5": "1d26cc225916d58b445afa1fc8025ef7"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "godot-class-graph-symbol-processor-0.14.3-4.5.1-92ac75f-SNAPSHOT-javadoc.jar",
          "url": "godot-class-graph-symbol-processor-0.14.3-4.5.1-92ac75f-SNAPSHOT-javadoc.jar",
          "size": 261,
          "sha512": "1c7ab2a42f3d0a425498adfefb0619523400b0e147e97544e332eb8f4b85e0696ee7215d20aa908104fb1d6cad64f28d628d7985224ef07dbccb76a015b92d2f",
          "sha256": "14b5116dffc6e16431c7e6f7a531286d7e79bb3ec9e40e0899f4a4266abca56c",
          "sha1": "971f7ef89e1e8ea382dbe5c894405e2e2b5062bb",
          "md5": "14300134d0cc65208305ba20b79f5faf"
        }
      ]
    }
  ]
}
