{
  "formatVersion": "1.1",
  "component": {
    "group": "com.utopia-rise",
    "module": "godot-gradle-plugin",
    "version": "0.13.0-4.4.1-afac9a3-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.13"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.10"
          }
        }
      ],
      "files": [
        {
          "name": "godot-gradle-plugin-0.13.0-4.4.1-afac9a3-SNAPSHOT.jar",
          "url": "godot-gradle-plugin-0.13.0-4.4.1-afac9a3-SNAPSHOT.jar",
          "size": 123483,
          "sha512": "dad4089a1ba1295732db6055e3161f8c0cc6593c8ace79221ddb315f5a42d0575042c92a41c9f9abee1f7ffa218f2a92b3e6504c57e8b9924e7c44ce687b408a",
          "sha256": "ecc571f08be7f379c7ce48a27bd5a60b85e316156f3bfd2d29beadeb8fb61a65",
          "sha1": "d121892eab98e81648ac1671ef7ed79673ab9e52",
          "md5": "cb3566e7fce5ff3cdbcf99ef98fb2ca8"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-gradle-plugin",
          "version": {
            "requires": "2.1.10"
          }
        },
        {
          "group": "com.gradleup.shadow",
          "module": "shadow-gradle-plugin",
          "version": {
            "requires": "8.3.6"
          }
        },
        {
          "group": "org.jetbrains.gradle.plugin.idea-ext",
          "module": "org.jetbrains.gradle.plugin.idea-ext.gradle.plugin",
          "version": {
            "requires": "1.1.10"
          }
        },
        {
          "group": "com.utopia-rise",
          "module": "godot-build-props",
          "version": {
            "requires": "0.13.0-4.4.1-afac9a3-SNAPSHOT"
          }
        },
        {
          "group": "com.utopia-rise",
          "module": "godot-plugins-common",
          "version": {
            "requires": "0.13.0-4.4.1-afac9a3-SNAPSHOT"
          }
        },
        {
          "group": "com.utopia-rise",
          "module": "tools-common",
          "version": {
            "requires": "0.13.0-4.4.1-afac9a3-SNAPSHOT"
          }
        },
        {
          "group": "com.utopia-rise",
          "module": "godot-class-graph-symbol-processor",
          "version": {
            "requires": "0.13.0-4.4.1-afac9a3-SNAPSHOT"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.10"
          }
        }
      ],
      "files": [
        {
          "name": "godot-gradle-plugin-0.13.0-4.4.1-afac9a3-SNAPSHOT.jar",
          "url": "godot-gradle-plugin-0.13.0-4.4.1-afac9a3-SNAPSHOT.jar",
          "size": 123483,
          "sha512": "dad4089a1ba1295732db6055e3161f8c0cc6593c8ace79221ddb315f5a42d0575042c92a41c9f9abee1f7ffa218f2a92b3e6504c57e8b9924e7c44ce687b408a",
          "sha256": "ecc571f08be7f379c7ce48a27bd5a60b85e316156f3bfd2d29beadeb8fb61a65",
          "sha1": "d121892eab98e81648ac1671ef7ed79673ab9e52",
          "md5": "cb3566e7fce5ff3cdbcf99ef98fb2ca8"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "godot-gradle-plugin-0.13.0-4.4.1-afac9a3-SNAPSHOT-javadoc.jar",
          "url": "godot-gradle-plugin-0.13.0-4.4.1-afac9a3-SNAPSHOT-javadoc.jar",
          "size": 261,
          "sha512": "03c41f7c4900ae3fb06f4d03720f7f1d233e8e675d4ffad1c3b41d562819660742b05d630592b1aae3949869b31ba498c4614f9f627a32c1f6fb5685517782d8",
          "sha256": "93eb86927f009e8ce123a32b0bd41c99e70e11a9a93cb1379c41f2d4c8f1a5c7",
          "sha1": "f9c5c208f7db5fd9d3aeec36be6d812dde6f90bc",
          "md5": "12b61d6882cb90117f7a1d66adac9a7e"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "godot-gradle-plugin-0.13.0-4.4.1-afac9a3-SNAPSHOT-sources.jar",
          "url": "godot-gradle-plugin-0.13.0-4.4.1-afac9a3-SNAPSHOT-sources.jar",
          "size": 39626,
          "sha512": "ac18d56ea1a3e037a4250a90b8bb948ed9dcfa835d54519bcf3e3563ba797d886bcf34d59dc557c1fa5d83f1b4c6c705a13e3c550cd3aa9035e8e1bd941857fa",
          "sha256": "144fa1b2f7492adcc64540dd05056c9c8d2d753ab080913c4d14346363fc330e",
          "sha1": "7359c8b25a1f33fcf29169e0062aed27037d3e6c",
          "md5": "6b784cf0c05723de024b89b925ca4d9a"
        }
      ]
    }
  ]
}
