{
  "formatVersion": "1.1",
  "component": {
    "group": "com.utopia-rise",
    "module": "godot-bootstrap-library-debug",
    "version": "0.14.3-4.5.1-92ac75f-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.13"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "com.utopia-rise",
          "module": "common",
          "version": {
            "requires": "0.14.3-4.5.1-92ac75f-SNAPSHOT"
          }
        },
        {
          "group": "com.utopia-rise",
          "module": "godot-api-library-debug",
          "version": {
            "requires": "0.14.3-4.5.1-92ac75f-SNAPSHOT"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.10"
          }
        }
      ],
      "files": [
        {
          "name": "godot-bootstrap-library-debug-0.14.3-4.5.1-92ac75f-SNAPSHOT.jar",
          "url": "godot-bootstrap-library-debug-0.14.3-4.5.1-92ac75f-SNAPSHOT.jar",
          "size": 72898,
          "sha512": "ece7a201be7c8fd38482574cb6b79f01bed96d7389c5b151c02ecc20933a8298ce22484643e34869b597292baea0a336e5dad29f130bc974b594f69d301546d9",
          "sha256": "236f6b428926866200ebe4734b9315843ed7bfae22e7f8670fa7c7eafa0be4ef",
          "sha1": "a3e3e40442d2597f4e4d709eea9ca11a780277d0",
          "md5": "c640444d2bba25aaf259090b46b270a3"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "com.utopia-rise",
          "module": "godot-internal-library-debug",
          "version": {
            "requires": "0.14.3-4.5.1-92ac75f-SNAPSHOT"
          }
        },
        {
          "group": "com.utopia-rise",
          "module": "common",
          "version": {
            "requires": "0.14.3-4.5.1-92ac75f-SNAPSHOT"
          }
        },
        {
          "group": "com.utopia-rise",
          "module": "godot-api-library-debug",
          "version": {
            "requires": "0.14.3-4.5.1-92ac75f-SNAPSHOT"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.10"
          }
        }
      ],
      "files": [
        {
          "name": "godot-bootstrap-library-debug-0.14.3-4.5.1-92ac75f-SNAPSHOT.jar",
          "url": "godot-bootstrap-library-debug-0.14.3-4.5.1-92ac75f-SNAPSHOT.jar",
          "size": 72898,
          "sha512": "ece7a201be7c8fd38482574cb6b79f01bed96d7389c5b151c02ecc20933a8298ce22484643e34869b597292baea0a336e5dad29f130bc974b594f69d301546d9",
          "sha256": "236f6b428926866200ebe4734b9315843ed7bfae22e7f8670fa7c7eafa0be4ef",
          "sha1": "a3e3e40442d2597f4e4d709eea9ca11a780277d0",
          "md5": "c640444d2bba25aaf259090b46b270a3"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "godot-bootstrap-library-debug-0.14.3-4.5.1-92ac75f-SNAPSHOT-sources.jar",
          "url": "godot-bootstrap-library-debug-0.14.3-4.5.1-92ac75f-SNAPSHOT-sources.jar",
          "size": 12109,
          "sha512": "6155a2b726e95259453def6c39a190d9b9d3505e65350d7a69bf592134fd6a7cfdb088215d30ddd3f5547c3c4e32e2c026da47158cb76f296de0e27ccae2356c",
          "sha256": "ed143e7a4fcb27a3a1b0965a663510eaa4a6e309fe4c055b8e293f2bbba012ac",
          "sha1": "8b01c8a3a359f7c83735c31dd317409e67b5abd0",
          "md5": "fc7d120fde68b8ae43575944c1e8958c"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "godot-bootstrap-library-debug-0.14.3-4.5.1-92ac75f-SNAPSHOT-javadoc.jar",
          "url": "godot-bootstrap-library-debug-0.14.3-4.5.1-92ac75f-SNAPSHOT-javadoc.jar",
          "size": 261,
          "sha512": "d2d5111cff05f4af2cb1f346f0072499da3f5fc30196aa948e9921f3feecf4718e0216edad0d796f2b0c45780ce06025b9561fde84de13ea14c2ee59ca5631b5",
          "sha256": "90cd715274b6eecc78a9d49648b0c8caa16830a1c6b1982a93d3ce9a907473f2",
          "sha1": "5935f0c88744937da03cd8f51629f0c0e6d6c063",
          "md5": "d590f0412bb2f21f103e75c1aff5e4e6"
        }
      ]
    }
  ]
}
