{
  "formatVersion": "1.1",
  "component": {
    "group": "com.utopia-rise",
    "module": "godot-extension-library-debug",
    "version": "0.14.3-4.5.1-92ac75f-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.13"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "com.utopia-rise",
          "module": "common",
          "version": {
            "requires": "0.14.3-4.5.1-92ac75f-SNAPSHOT"
          }
        },
        {
          "group": "com.utopia-rise",
          "module": "godot-core-library-debug",
          "version": {
            "requires": "0.14.3-4.5.1-92ac75f-SNAPSHOT"
          }
        },
        {
          "group": "com.utopia-rise",
          "module": "godot-api-library-debug",
          "version": {
            "requires": "0.14.3-4.5.1-92ac75f-SNAPSHOT"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.10"
          }
        }
      ],
      "files": [
        {
          "name": "godot-extension-library-debug-0.14.3-4.5.1-92ac75f-SNAPSHOT.jar",
          "url": "godot-extension-library-debug-0.14.3-4.5.1-92ac75f-SNAPSHOT.jar",
          "size": 47673,
          "sha512": "26a55a78bad6d7894e35c5b61579d60aa18c58fa94918c851d4abba3b4ffeebe7326e798d1d0f789a7c51d7af4371c01c42fb4ecdaa8732dfbe9279fa74dcc58",
          "sha256": "564cbd9881e9e4fc6beeed5162a570dfab58dd1cc108acbfc19b8072e5d707b7",
          "sha1": "7728e9d83a07fcaa5b9143daaf1b531721c99b47",
          "md5": "2aff01544be1d07531fa9550a9568478"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "com.utopia-rise",
          "module": "godot-internal-library-debug",
          "version": {
            "requires": "0.14.3-4.5.1-92ac75f-SNAPSHOT"
          }
        },
        {
          "group": "com.utopia-rise",
          "module": "common",
          "version": {
            "requires": "0.14.3-4.5.1-92ac75f-SNAPSHOT"
          }
        },
        {
          "group": "com.utopia-rise",
          "module": "godot-core-library-debug",
          "version": {
            "requires": "0.14.3-4.5.1-92ac75f-SNAPSHOT"
          }
        },
        {
          "group": "com.utopia-rise",
          "module": "godot-api-library-debug",
          "version": {
            "requires": "0.14.3-4.5.1-92ac75f-SNAPSHOT"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.10"
          }
        }
      ],
      "files": [
        {
          "name": "godot-extension-library-debug-0.14.3-4.5.1-92ac75f-SNAPSHOT.jar",
          "url": "godot-extension-library-debug-0.14.3-4.5.1-92ac75f-SNAPSHOT.jar",
          "size": 47673,
          "sha512": "26a55a78bad6d7894e35c5b61579d60aa18c58fa94918c851d4abba3b4ffeebe7326e798d1d0f789a7c51d7af4371c01c42fb4ecdaa8732dfbe9279fa74dcc58",
          "sha256": "564cbd9881e9e4fc6beeed5162a570dfab58dd1cc108acbfc19b8072e5d707b7",
          "sha1": "7728e9d83a07fcaa5b9143daaf1b531721c99b47",
          "md5": "2aff01544be1d07531fa9550a9568478"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "godot-extension-library-debug-0.14.3-4.5.1-92ac75f-SNAPSHOT-sources.jar",
          "url": "godot-extension-library-debug-0.14.3-4.5.1-92ac75f-SNAPSHOT-sources.jar",
          "size": 14714,
          "sha512": "1c290f14d1db5eb8ad00d27a069f8af8a97f3149ec0c914f150c8987b4bc6310ef9c2737e4ecd8317e7af9d3e51847c0a22881b6331072c527ba4330d232fa3e",
          "sha256": "d3f777a8374ff3d81786163da55c97505c9a316605dbcbc3785bfbfef42904e3",
          "sha1": "f3c68824910e6d3523aefd09b0aa93521e8872b4",
          "md5": "26159d4677be2d54fbe15d3dcd7fc97b"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "godot-extension-library-debug-0.14.3-4.5.1-92ac75f-SNAPSHOT-javadoc.jar",
          "url": "godot-extension-library-debug-0.14.3-4.5.1-92ac75f-SNAPSHOT-javadoc.jar",
          "size": 261,
          "sha512": "d2d5111cff05f4af2cb1f346f0072499da3f5fc30196aa948e9921f3feecf4718e0216edad0d796f2b0c45780ce06025b9561fde84de13ea14c2ee59ca5631b5",
          "sha256": "90cd715274b6eecc78a9d49648b0c8caa16830a1c6b1982a93d3ce9a907473f2",
          "sha1": "5935f0c88744937da03cd8f51629f0c0e6d6c063",
          "md5": "d590f0412bb2f21f103e75c1aff5e4e6"
        }
      ]
    }
  ]
}
