{
  "formatVersion": "1.1",
  "component": {
    "group": "com.utopia-rise",
    "module": "godot-build-props",
    "version": "0.14.3-4.5.1-92ac75f-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.13"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.10"
          }
        }
      ],
      "files": [
        {
          "name": "godot-build-props-0.14.3-4.5.1-92ac75f-SNAPSHOT.jar",
          "url": "godot-build-props-0.14.3-4.5.1-92ac75f-SNAPSHOT.jar",
          "size": 3157,
          "sha512": "0720df3627d8b371f76309a6aca70ea63da9d5d7776401241e812f29abe39905e47cd39daa3a67451dc2ade1792ce392015f9e621a32f7bd01ee4214081653eb",
          "sha256": "1227682f6cf027a0876fcae04332af6f7484d2c17c679c2a52d0a679e6e13667",
          "sha1": "da2366a825091d6aa07ad65085616eb672c060ec",
          "md5": "461beaebcd49e98b90ebe506bebd9cdc"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.10"
          }
        }
      ],
      "files": [
        {
          "name": "godot-build-props-0.14.3-4.5.1-92ac75f-SNAPSHOT.jar",
          "url": "godot-build-props-0.14.3-4.5.1-92ac75f-SNAPSHOT.jar",
          "size": 3157,
          "sha512": "0720df3627d8b371f76309a6aca70ea63da9d5d7776401241e812f29abe39905e47cd39daa3a67451dc2ade1792ce392015f9e621a32f7bd01ee4214081653eb",
          "sha256": "1227682f6cf027a0876fcae04332af6f7484d2c17c679c2a52d0a679e6e13667",
          "sha1": "da2366a825091d6aa07ad65085616eb672c060ec",
          "md5": "461beaebcd49e98b90ebe506bebd9cdc"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "godot-build-props-0.14.3-4.5.1-92ac75f-SNAPSHOT-sources.jar",
          "url": "godot-build-props-0.14.3-4.5.1-92ac75f-SNAPSHOT-sources.jar",
          "size": 1137,
          "sha512": "2d5793fc3bdceb8da87d16a62630355e8f1b8647e8805fa10c2e857b8941a10ad4a155518806aec0f3c86381a513d24782a0c46ba5de47e1b535bd39b621f858",
          "sha256": "577fe9a9d33a53daad9512786ed3be05082da36b65c3e1fa01c3ef4d56c9674f",
          "sha1": "041f43823bef36b81b3bb456b310bc3c0d8080e9",
          "md5": "bc2c32af6ea1a874c790d3c9813bfb34"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "godot-build-props-0.14.3-4.5.1-92ac75f-SNAPSHOT-javadoc.jar",
          "url": "godot-build-props-0.14.3-4.5.1-92ac75f-SNAPSHOT-javadoc.jar",
          "size": 261,
          "sha512": "7dec13297af6949001af3d429e6e813dcdaf9d7618c3aafc27dd057504e486c0141a3a43eb80ccbe92770f87d2c96766a894519beb68b0b045cde054493f910e",
          "sha256": "47ca5b06147b2426cd1622a30049ba517ca36ff24a0713bb1f31b4bca042d671",
          "sha1": "5dab97305e91b4b73d59bb0c9b3049faf93c0b47",
          "md5": "135fc3e5a8f624eeba1370b1b3dd63a7"
        }
      ]
    }
  ]
}
