{
  "formatVersion": "1.1",
  "component": {
    "group": "com.utopia-rise",
    "module": "godot-entry-generator",
    "version": "0.13.0-4.4.1-afac9a3-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.13"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.10"
          }
        }
      ],
      "files": [
        {
          "name": "godot-entry-generator-0.13.0-4.4.1-afac9a3-SNAPSHOT.jar",
          "url": "godot-entry-generator-0.13.0-4.4.1-afac9a3-SNAPSHOT.jar",
          "size": 181472,
          "sha512": "0af3341014bd8d4c1bd5172cdd21b64f883d1dd2d99d2d3deba9737a3e08f4e694fd693a8e2554df8ae1c180c7b1014e82b5f2d8a52ade61fd92c255c239a748",
          "sha256": "7a40108b268217e0106759a860275e6694905ec747d4b0b24a3f86b6530a065c",
          "sha1": "9164723463681f122bf3798547c3a949a2d8c289",
          "md5": "cff053516e6adb5a386a0f737d3a11a2"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "com.utopia-rise",
          "module": "tools-common",
          "version": {
            "requires": "0.13.0-4.4.1-afac9a3-SNAPSHOT"
          }
        },
        {
          "group": "com.utopia-rise",
          "module": "godot-core-library-debug",
          "version": {
            "requires": "0.13.0-4.4.1-afac9a3-SNAPSHOT"
          }
        },
        {
          "group": "com.squareup",
          "module": "kotlinpoet",
          "version": {
            "requires": "1.12.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.10"
          }
        }
      ],
      "files": [
        {
          "name": "godot-entry-generator-0.13.0-4.4.1-afac9a3-SNAPSHOT.jar",
          "url": "godot-entry-generator-0.13.0-4.4.1-afac9a3-SNAPSHOT.jar",
          "size": 181472,
          "sha512": "0af3341014bd8d4c1bd5172cdd21b64f883d1dd2d99d2d3deba9737a3e08f4e694fd693a8e2554df8ae1c180c7b1014e82b5f2d8a52ade61fd92c255c239a748",
          "sha256": "7a40108b268217e0106759a860275e6694905ec747d4b0b24a3f86b6530a065c",
          "sha1": "9164723463681f122bf3798547c3a949a2d8c289",
          "md5": "cff053516e6adb5a386a0f737d3a11a2"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "godot-entry-generator-0.13.0-4.4.1-afac9a3-SNAPSHOT-sources.jar",
          "url": "godot-entry-generator-0.13.0-4.4.1-afac9a3-SNAPSHOT-sources.jar",
          "size": 49064,
          "sha512": "d1fd36dd436d61d0d94fadca5237e5b7462a50760bc01f2b9d5a2a4a53cdf483fbae6e6cbced22c574b654333c5878d2204b5718de364168a2842374912bc5ff",
          "sha256": "d30715e8676e44175b2bf9faf8a4e53ff9765feb23a252bf2cf42889814a0f97",
          "sha1": "d213fe9f05c8647b6b523b72d3e811d6b417b3a7",
          "md5": "c6bfc99d291861da3d0fa6c89b1320dd"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "godot-entry-generator-0.13.0-4.4.1-afac9a3-SNAPSHOT-javadoc.jar",
          "url": "godot-entry-generator-0.13.0-4.4.1-afac9a3-SNAPSHOT-javadoc.jar",
          "size": 261,
          "sha512": "03c41f7c4900ae3fb06f4d03720f7f1d233e8e675d4ffad1c3b41d562819660742b05d630592b1aae3949869b31ba498c4614f9f627a32c1f6fb5685517782d8",
          "sha256": "93eb86927f009e8ce123a32b0bd41c99e70e11a9a93cb1379c41f2d4c8f1a5c7",
          "sha1": "f9c5c208f7db5fd9d3aeec36be6d812dde6f90bc",
          "md5": "12b61d6882cb90117f7a1d66adac9a7e"
        }
      ]
    }
  ]
}
