{
  "formatVersion": "1.1",
  "component": {
    "group": "com.utopia-rise",
    "module": "tools-common",
    "version": "0.14.3-4.5.1-92ac75f-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.13"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "com.utopia-rise",
          "module": "common",
          "version": {
            "requires": "0.14.3-4.5.1-92ac75f-SNAPSHOT"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.10"
          }
        }
      ],
      "files": [
        {
          "name": "tools-common-0.14.3-4.5.1-92ac75f-SNAPSHOT.jar",
          "url": "tools-common-0.14.3-4.5.1-92ac75f-SNAPSHOT.jar",
          "size": 21011,
          "sha512": "dd15855ac6df219d5b84ed3938e3f52a5d26f4bf9e70b1679cf05c96dd193ef910f2dbbc8215306d77d13fcb69afa2fbbc25ee42288f86fc5b568530e750f0ee",
          "sha256": "944e086108d2604491589084c69b09a0703225da24014b5cf310526a9777ea14",
          "sha1": "357a66cc17d50abab67549292b1deaa32e4b293c",
          "md5": "80db061b40d2352174cdb7cd3b63375a"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "com.squareup",
          "module": "kotlinpoet",
          "version": {
            "requires": "1.12.0"
          }
        },
        {
          "group": "com.utopia-rise",
          "module": "common",
          "version": {
            "requires": "0.14.3-4.5.1-92ac75f-SNAPSHOT"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.10"
          }
        }
      ],
      "files": [
        {
          "name": "tools-common-0.14.3-4.5.1-92ac75f-SNAPSHOT.jar",
          "url": "tools-common-0.14.3-4.5.1-92ac75f-SNAPSHOT.jar",
          "size": 21011,
          "sha512": "dd15855ac6df219d5b84ed3938e3f52a5d26f4bf9e70b1679cf05c96dd193ef910f2dbbc8215306d77d13fcb69afa2fbbc25ee42288f86fc5b568530e750f0ee",
          "sha256": "944e086108d2604491589084c69b09a0703225da24014b5cf310526a9777ea14",
          "sha1": "357a66cc17d50abab67549292b1deaa32e4b293c",
          "md5": "80db061b40d2352174cdb7cd3b63375a"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "tools-common-0.14.3-4.5.1-92ac75f-SNAPSHOT-sources.jar",
          "url": "tools-common-0.14.3-4.5.1-92ac75f-SNAPSHOT-sources.jar",
          "size": 5374,
          "sha512": "ff3e6f26f12fde09f67a55d0e292085109895bac39499ac3dca31e384a906c86b5c071b9222845e5c23357137dd5cb0458922e810bdc63cc49946c31cdcac8d4",
          "sha256": "ed01bfbd4ef01c95e23b6f936c8158040e8c35c9a40e3083e6257b4c47a6162e",
          "sha1": "c8cd9b641f80936bbb4834a502ab8bd2f017e0fe",
          "md5": "7782a016727ca4613580275f6f6dba3f"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "tools-common-0.14.3-4.5.1-92ac75f-SNAPSHOT-javadoc.jar",
          "url": "tools-common-0.14.3-4.5.1-92ac75f-SNAPSHOT-javadoc.jar",
          "size": 261,
          "sha512": "89091997cb5c0caed5c651c1cb708b85b549d349508857c7a2d558dec5fab30a153250968f5eb6703e6c1e1dd11689c8536c4aee5ef5dd49743cfcf4c8174027",
          "sha256": "bb895823fad354aab04e1d12a897b0229cad18a99cee4be0303153c38ddebe92",
          "sha1": "0b64db4a772f76d6f5ad5b43185535a97931d6f7",
          "md5": "302d8c8a06b67ad0f7d61db9092c8041"
        }
      ]
    }
  ]
}
