{
  "formatVersion": "1.1",
  "component": {
    "group": "com.utopia-rise",
    "module": "godot-plugins-common",
    "version": "0.14.3-4.5.1-92ac75f-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.13"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.10"
          }
        }
      ],
      "files": [
        {
          "name": "godot-plugins-common-0.14.3-4.5.1-92ac75f-SNAPSHOT-base.jar",
          "url": "godot-plugins-common-0.14.3-4.5.1-92ac75f-SNAPSHOT-base.jar",
          "size": 4739,
          "sha512": "31f27b4e0e7a3642e2b973618c072cdb7411e7f0f00d2df16883c38f808b7783352f0b9a3f8ac92434a72488675d391c3ea71201cb088e385593f3862c4279d8",
          "sha256": "734c02632253e74bc11afa84a8d117beb59d5e026923303369535710a8deeac7",
          "sha1": "64af69c2df0950c51e858572edd09aceae7e7c2c",
          "md5": "26543b7288741cb952451b78de0c49a9"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "com.utopia-rise",
          "module": "godot-build-props",
          "version": {
            "requires": "0.14.3-4.5.1-92ac75f-SNAPSHOT"
          }
        },
        {
          "group": "com.utopia-rise",
          "module": "tools-common",
          "version": {
            "requires": "0.14.3-4.5.1-92ac75f-SNAPSHOT"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.10"
          }
        }
      ],
      "files": [
        {
          "name": "godot-plugins-common-0.14.3-4.5.1-92ac75f-SNAPSHOT-base.jar",
          "url": "godot-plugins-common-0.14.3-4.5.1-92ac75f-SNAPSHOT-base.jar",
          "size": 4739,
          "sha512": "31f27b4e0e7a3642e2b973618c072cdb7411e7f0f00d2df16883c38f808b7783352f0b9a3f8ac92434a72488675d391c3ea71201cb088e385593f3862c4279d8",
          "sha256": "734c02632253e74bc11afa84a8d117beb59d5e026923303369535710a8deeac7",
          "sha1": "64af69c2df0950c51e858572edd09aceae7e7c2c",
          "md5": "26543b7288741cb952451b78de0c49a9"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "godot-plugins-common-0.14.3-4.5.1-92ac75f-SNAPSHOT-sources.jar",
          "url": "godot-plugins-common-0.14.3-4.5.1-92ac75f-SNAPSHOT-sources.jar",
          "size": 2075,
          "sha512": "c1c2c89d76bb04693ea8df19e0c8bebe44f16a074362d150e4e70d952b223aa9fc6a4c1e6955d0c071c9dab2eb8d1d0d5135287f66fb36d5035e7e7939d7440e",
          "sha256": "42ee79d4e5d0054fe134332ab2a824207e9cf6c1520bcb42a323a883c9947376",
          "sha1": "04398005aba4b446068d11a2f67750cf1588cefd",
          "md5": "4894ca2096e8b93437d6eceb1b85340c"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "godot-plugins-common-0.14.3-4.5.1-92ac75f-SNAPSHOT-javadoc.jar",
          "url": "godot-plugins-common-0.14.3-4.5.1-92ac75f-SNAPSHOT-javadoc.jar",
          "size": 261,
          "sha512": "88dee930c5a7b75782d066e4fee2746b758cb438f71c2cde6b75b1dddfecc93875980d0f24676058fd7fe2a2231ff6059a59281e95a6ab59ff183fc8e8e5bdba",
          "sha256": "34ea030f02666c350bdb62d6043192a3f036a673f82f6fe9b74264b66cc7920f",
          "sha1": "46a84e6576437cae64579997e0e8df216df32f7a",
          "md5": "3e56b5228b92fa5ae955b30a5721c423"
        }
      ]
    }
  ]
}
